

FROM python:3.11-slim

WORKDIR /app


# Copy requirements first
COPY requirements.txt .


# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Copy project files
COPY . .


EXPOSE 3000


CMD ["python", "app.py"]

