"""add workflow tracking fields

Revision ID: 8fa9f66c3016
Revises: c6acf5489875
Create Date: 2026-05-21 16:24:43.559507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa9f66c3016'
down_revision = 'c6acf5489875'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retry_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('error_message')
        batch_op.drop_column('retry_count')

    # ### end Alembic commands ###
